[2021-07-15 11:38:46,684] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Treino-02.get-data 2021-07-14T12:26:00+00:00 [queued]>
[2021-07-15 11:38:46,694] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Treino-02.get-data 2021-07-14T12:26:00+00:00 [queued]>
[2021-07-15 11:38:46,694] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 11:38:46,694] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-15 11:38:46,695] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 11:38:46,707] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): get-data> on 2021-07-14T12:26:00+00:00
[2021-07-15 11:38:46,711] {standard_task_runner.py:52} INFO - Started process 8976 to run task
[2021-07-15 11:38:46,717] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Treino-02', 'get-data', '2021-07-14T12:26:00+00:00', '--job-id', '1636', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmphvzkhsh3', '--error-file', '/tmp/tmpdvguguvi']
[2021-07-15 11:38:46,718] {standard_task_runner.py:77} INFO - Job 1636: Subtask get-data
[2021-07-15 11:38:46,819] {logging_mixin.py:104} INFO - Running <TaskInstance: Treino-02.get-data 2021-07-14T12:26:00+00:00 [running]> on host 07e9e45ed309
[2021-07-15 11:38:46,911] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=bruno@***.com.br,bruno@bruno.com.br
AIRFLOW_CTX_DAG_OWNER=Bruno - IGTI
AIRFLOW_CTX_DAG_ID=Treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T12:26:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-14T12:26:00+00:00
[2021-07-15 11:38:46,912] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-15 11:38:46,913] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'curl https://raw.githubusercontent.com/A3Data/hermione/master/hermione/file_text/train.csv -o ~/train.csv']
[2021-07-15 11:38:46,922] {subprocess.py:75} INFO - Output:
[2021-07-15 11:38:46,929] {subprocess.py:79} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2021-07-15 11:38:46,930] {subprocess.py:79} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2021-07-15 11:38:46,991] {subprocess.py:79} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /home/***/train.csv: Permission denied
[2021-07-15 11:38:46,991] {subprocess.py:79} INFO - 100    14  100    14    0     0    225      0 --:--:-- --:--:-- --:--:--   222
[2021-07-15 11:38:46,992] {subprocess.py:79} INFO - curl: (23) Failed writing body (0 != 14)
[2021-07-15 11:38:46,993] {subprocess.py:83} INFO - Command exited with return code 23
[2021-07-15 11:38:47,007] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-15 11:38:47,010] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Treino-02, task_id=get-data, execution_date=20210714T122600, start_date=20210715T113846, end_date=20210715T113847
[2021-07-15 11:38:47,061] {local_task_job.py:151} INFO - Task exited with return code 1
