[2021-07-15 11:34:54,708] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Treino-02.get-data 2021-07-14T11:08:00+00:00 [queued]>
[2021-07-15 11:34:54,720] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Treino-02.get-data 2021-07-14T11:08:00+00:00 [queued]>
[2021-07-15 11:34:54,721] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 11:34:54,721] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-07-15 11:34:54,721] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 11:34:54,735] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): get-data> on 2021-07-14T11:08:00+00:00
[2021-07-15 11:34:54,739] {standard_task_runner.py:52} INFO - Started process 8308 to run task
[2021-07-15 11:34:54,744] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Treino-02', 'get-data', '2021-07-14T11:08:00+00:00', '--job-id', '1545', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmpr6fup26c', '--error-file', '/tmp/tmp55r5prxh']
[2021-07-15 11:34:54,744] {standard_task_runner.py:77} INFO - Job 1545: Subtask get-data
[2021-07-15 11:34:54,793] {logging_mixin.py:104} INFO - Running <TaskInstance: Treino-02.get-data 2021-07-14T11:08:00+00:00 [running]> on host 07e9e45ed309
[2021-07-15 11:34:54,871] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=bruno@***.com.br,bruno@bruno.com.br
AIRFLOW_CTX_DAG_OWNER=Bruno - IGTI
AIRFLOW_CTX_DAG_ID=Treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T11:08:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-14T11:08:00+00:00
[2021-07-15 11:34:54,872] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-15 11:34:54,873] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'curl https://raw.githubusercontent.com/A3Data/hermione/master/hermione/file_text/train.csv -o ~/train.csv']
[2021-07-15 11:34:54,889] {subprocess.py:75} INFO - Output:
[2021-07-15 11:34:54,895] {subprocess.py:79} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2021-07-15 11:34:54,895] {subprocess.py:79} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2021-07-15 11:34:54,978] {subprocess.py:79} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /home/***/train.csv: Permission denied
[2021-07-15 11:34:54,978] {subprocess.py:79} INFO - 100    14  100    14    0     0    170      0 --:--:-- --:--:-- --:--:--   168
[2021-07-15 11:34:54,978] {subprocess.py:79} INFO - curl: (23) Failed writing body (0 != 14)
[2021-07-15 11:34:54,982] {subprocess.py:83} INFO - Command exited with return code 23
[2021-07-15 11:34:54,993] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-15 11:34:54,995] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=Treino-02, task_id=get-data, execution_date=20210714T110800, start_date=20210715T113454, end_date=20210715T113454
[2021-07-15 11:34:55,033] {local_task_job.py:151} INFO - Task exited with return code 1
